# Generated by Django 3.2.5 on 2021-07-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ghg', models.IntegerField()),
                ('food_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('best_match', models.CharField(max_length=20)),
                ('best_match_id', models.IntegerField()),
                ('density', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('ghg', models.IntegerField()),
                ('land_use', models.IntegerField()),
                ('water_use', models.IntegerField()),
                ('jan_storage', models.FloatField()),
                ('jan_harvest', models.IntegerField()),
                ('feb_storage', models.FloatField()),
                ('feb_harvest', models.IntegerField()),
                ('mar_storage', models.FloatField()),
                ('mar_harvest', models.IntegerField()),
                ('apr_storage', models.FloatField()),
                ('apr_harvest', models.IntegerField()),
                ('jun_storage', models.FloatField()),
                ('jun_harvest', models.IntegerField()),
                ('jul_storage', models.FloatField()),
                ('jul_harvest', models.IntegerField()),
                ('aug_storage', models.FloatField()),
                ('aug_harvest', models.IntegerField()),
                ('sep_storage', models.FloatField()),
                ('sep_harvest', models.IntegerField()),
                ('oct_storage', models.FloatField()),
                ('oct_harvest', models.IntegerField()),
                ('nov_storage', models.FloatField()),
                ('nov_harvest', models.IntegerField()),
                ('dec_storage', models.FloatField()),
                ('dec_harvest', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterdata')),
            ],
            options={
                'ordering': ['food_id'],
            },
        ),
        migrations.CreateModel(
            name='PortionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('food_unit', models.CharField(max_length=20)),
                ('mass', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterdata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FoodonIds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('foodon_id', models.TextField(max_length=50)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterdata')),
            ],
            options={
                'ordering': ['food_id'],
            },
        ),
        migrations.CreateModel(
            name='AlternateNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('alternate_name', models.CharField(max_length=30)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterdata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
