# Generated by Django 3.2.5 on 2021-07-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlternateNames',
            new_name='AlternateName',
        ),
        migrations.RenameModel(
            old_name='FoodonIds',
            new_name='FoodonId',
        ),
        migrations.AlterModelOptions(
            name='referencedata',
            options={'ordering': ['food_name']},
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='apr_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='apr_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='aug_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='aug_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='dec_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='dec_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='feb_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='feb_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jan_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jan_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jul_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jul_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jun_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='jun_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='mar_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='mar_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='nov_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='nov_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='oct_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='oct_storage',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='sep_harvest',
        ),
        migrations.RemoveField(
            model_name='referencedata',
            name='sep_storage',
        ),
        migrations.CreateModel(
            name='SeasonalityData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
                ('land_use_change', models.IntegerField()),
                ('feed', models.IntegerField()),
                ('farm', models.IntegerField()),
                ('processing', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('packaging', models.IntegerField()),
                ('retail', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterdata')),
            ],
        ),
    ]
