# Generated by Django 3.2.5 on 2021-08-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210802_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdata',
            old_name='ghg',
            new_name='ghg_global',
        ),
        migrations.RenameField(
            model_name='seasonalitydata',
            old_name='month',
            new_name='ghg',
        ),
        migrations.RemoveField(
            model_name='seasonalitydata',
            name='food_id',
        ),
        migrations.AddField(
            model_name='masterdata',
            name='ghg_retail',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
