# Generated by Django 3.2.5 on 2021-08-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210806_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedata',
            name='farm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='feed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='land_use_change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='packaging',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='processing',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='retail',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencedata',
            name='transport',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonalitydata',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonalitydata',
            name='reference_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.referencedata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='best_match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.referencedata'),
        ),
    ]
