# Generated by Django 3.2.5 on 2021-08-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210806_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portiondata',
            old_name='food_unit',
            new_name='portion',
        ),
        migrations.RenameField(
            model_name='portiondata',
            old_name='mass',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='portiondata',
            name='description',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
