# Generated by Django 3.2.5 on 2021-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210806_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiondata',
            name='description',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
